# Generated by Django 5.1.3 on 2024-12-10 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="employee",
            new_name="User",
        ),
    ]
